name: spotify_clone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  hydrated_bloc: ^9.1.5
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  cloud_firestore: ^4.14.0
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

fonts:
    - family: Satoshi
      fonts:
        - assets: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - assets: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - assets: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - assets: assets/fonts/Satoshi-Regular.ttf
          wegith: 400
        - assets: assets/fonts/Satoshi-Light.ttf
          weight: 300